reviews:
  max_file_size: 5000  # Allow review of large files
  skip_large_files: false  # Force review of long scripts
  review_status: false  # Hide skipped file warnings
  path_filters:
    - '!.*'  # Exclude ALL hidden folders (e.g., .git, .vscode, .cache)
    - '!CNMF-e/OASIS_matlab/**'
    - '!CNMF-e/ca_source_extraction/**'
    - '!Dendrite Imaging/**'
    - '!Demo/**'  # If demo files don't need review
    - '!**/*.h5'  # Exclude binary HDF5 files
    - '!**/.DS_Store'  # Exclude macOS system files
    - '!Align_sessions/codegen/**'  # Exclude generated code
    - '!Motion_Correction/NoRMCorre-master/**'  # Exclude external library
    - '!**/*.asv'  # Exclude autosave files