site_name: CaliAli
site_url: https://caliali-pv.github.io/CaliAli/
theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - version-dropdown   # The dropdown in your navigation
    - version-badge     # The “badge” near the title
  language: en
  palette:
  
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
      
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
      
plugins:
  - search
  - tags
  - mike

  

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CaliAli-PV/CaliAli
    - icon: fontawesome/solid/file-lines
      link: https://www.biorxiv.org/content/10.1101/2023.05.19.540935v1
  version:
    provider: mike
    alias: true
     

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
nav:

      - Index: index.md    
      - About CaliAli: Intro.md
      - Installation and system requirements: Usage.md
      - Getting started: demo_data.md
      - Downsampling and Motion correction: Prep.md
      - Inter-session Alignment: alignment.md
      - Calcium Signal extraction with CaliAli: extraction.md
      - Post Processing: Post.md
      - Utilities: Utilities.md
      - TL;DR: TLDR.md


copyright: |
  &copy; 2024 <a href="https://github.com/CaliAli-PV/CaliAli"  target="_blank" rel="noopener">CaliAli</a>

