site_name: CaliAli
site_url: https://www.biorxiv.org/content/10.1101/2023.05.19.540935v1
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - navigation.instant
    
  language: en
  palette:
  
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
      
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
      
plugins:
  - search
  - tags

validation:
  omitted_files: ignore
  unrecognized_links: warn

  

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CaliAli-PV/CaliAli
    - icon: fontawesome/solid/file-lines
      link: https://www.nature.com/articles/s41467-025-58817-z
  version:
    provider: mike
    warning: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
nav:
      - Home: index.md    
      - Getting Started: Getting_started.md
      - Installation and System Requirements: Installation.md
      - Setting CaliAli Parameters: Parameters.md
      - Downsampling: Downsampling.md
      - Motion Correction: Motion_correction.md
      - Inter-session Alignment: alignment.md
      - Calcium Signal extraction with CaliAli: extraction.md
      - Low-Memory Processing: Low_memory.md
      - Whats new?: Version_History.md
      - Usage Agreement: License.md
      - CaliAli Parameters Overview: Parameters_index.md
      - List of Relevant functions: function_index.md


extra_css:
  - overrides/main.css


copyright: |
  &copy; 2025 <a href="License"  target="_blank" rel="noopener">CaliAli</a>
