site_name: CaliAli
site_url: https://www.biorxiv.org/content/10.1101/2023.05.19.540935v1
theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
plugins:
  - search
  - mkdocs-video
  - privacy
  - offline
  

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CaliAli-PV/CaliAli
    - icon: fontawesome/solid/file-lines
      link: https://www.biorxiv.org/content/10.1101/2023.05.19.540935v1

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  
nav:

      - Index: index.md    
      - About CaliAli: Intro.md
      - Installation and system requirements: Usage.md
      - Getting started: demo_data.md
      - Downsampling and Motion correction: Prep.md
      - Inter-session Alignment: alignment.md
      - Calcium Signal extraction with CaliAli: extraction.md
      - Post Processing: Post.md
      - Utilities: Utilities.md


copyright: |
  &copy; 2023 <a href="https://github.com/CaliAli-PV/CaliAli"  target="_blank" rel="noopener">Pablo Vergara</a>
