function bool=swap_conditions(assign,j,l,session_ids,n,change)


bool=assign(l)~=assign(j)&l>j&...
~any(session_ids(l)==(session_ids((assign==assign(j))&((1:n)'~=j))))&...
~any(session_ids(j)==(session_ids((assign==assign(l))&((1:n)'~=l))))&...
(isempty(change)||(ismember(assign(l),change)||ismember(assign(j),change)));
